
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package br.edu.analisador.model;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Chave_Fechar = 25;
  public static final int Else = 8;
  public static final int Op_Incremento = 20;
  public static final int For = 11;
  public static final int Numero = 31;
  public static final int Divisao = 16;
  public static final int Op_Logico = 17;
  public static final int Op_Booleano = 21;
  public static final int Tipo_Dado = 4;
  public static final int Identificador = 30;
  public static final int Int = 5;
  public static final int Citacoes = 3;
  public static final int Subtracao = 14;
  public static final int Main = 28;
  public static final int Chave_Abrir = 24;
  public static final int Parenteses_Abrir = 22;
  public static final int Caractere = 6;
  public static final int EOF = 0;
  public static final int Fim_Comando = 29;
  public static final int Colchete_Abrir = 26;
  public static final int Multiplicacao = 15;
  public static final int If = 7;
  public static final int error = 1;
  public static final int Linha = 2;
  public static final int Erro = 32;
  public static final int Do = 9;
  public static final int Soma = 13;
  public static final int Op_Atribuicao = 19;
  public static final int Igual = 12;
  public static final int Colchete_Fechar = 27;
  public static final int Op_Relacional = 18;
  public static final int While = 10;
  public static final int Parenteses_Fechar = 23;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Linha",
  "Citacoes",
  "Tipo_Dado",
  "Int",
  "Caractere",
  "If",
  "Else",
  "Do",
  "While",
  "For",
  "Igual",
  "Soma",
  "Subtracao",
  "Multiplicacao",
  "Divisao",
  "Op_Logico",
  "Op_Relacional",
  "Op_Atribuicao",
  "Op_Incremento",
  "Op_Booleano",
  "Parenteses_Abrir",
  "Parenteses_Fechar",
  "Chave_Abrir",
  "Chave_Fechar",
  "Colchete_Abrir",
  "Colchete_Fechar",
  "Main",
  "Fim_Comando",
  "Identificador",
  "Numero",
  "Erro"
  };
}

